---
- hosts: all
  gather_facts: no

  tasks:
    - name: Include Var files
      include_vars: "{{ item }}"
      with_fileglob:
        - vars.yml
        - local.yml

    - name: Configure EPEL
      yum:
        name: epel-release
        state: present
      become: yes

    - name: Install Build Tools and common dependencies
      yum:
        name: "{{ dependencies }}"
        state: present
      become: yes

    - name: Install Cairo Development libs
      yum:
        name: cairo-devel
        state: present
      become: yes
      when: with_cairo == true

    - name: Install Exempi Development libs
      yum:
        name: exempi-devel
        state: present
      become: yes
      when: with_exempi == true

    - name: Install Fcgi Development libs
      yum:
        name: fcgi-devel
        state: present
      become: yes
      when: with_fcgi == true

    - name: Install fribidi Development libs
      yum:
        name: fribidi-devel
        state: present
      become: yes
      when: with_fribidi == true

    - name: Install gdal Development libs
      yum:
        name: gdal-devel
        state: present
      become: yes
      when: with_gdal == true

    - name: Install geos Development libs
      yum:
        name: geos-devel
        state: present
      become: yes
      when: with_geos == true

    - name: Install GIF Development libs
      yum:
        name: giflib-devel
        state: present
      become: yes
      when: with_gif == true

    - name: Install Harfbuzz Development libs
      yum:
        name: harfbuzz-devel
        state: present
      become: yes
      when: with_harfbuzz == true

    - name: Install Curl Development libs
      yum:
        name: libcurl-devel
        state: present
      become: yes
      when: with_curl == true

    - name: Install librsvg2 Development libs
      yum:
        name: librsvg2-devel
        state: present
      become: yes
      when: with_rsvg == true

    - name: Install libxml2 Development libs
      yum:
        name: libxml2-devel
        state: present
      become: yes
      when: with_libxml2 == true or with_sos == true or with_kml == true

    - name: Install PHP Development libs
      yum:
        name: php-devel
        state: present
      become: yes
      when: with_php == true

    - name: Install Proj Development libs
      yum:
        name: proj-devel
        state: present
      become: yes
      when: with_proj == true

    - name: Install Protobuf-c Development libs
      yum:
        name: protobuf-c-devel
        state: present
      become: yes
      when: with_protobufc == true

    - name: Install FPM Ruby gem
      gem:
        name: fpm
        state: present

    - name: Download MapServer Source Package
      unarchive:
        src: "http://download.osgeo.org/mapserver/mapserver-{{mapserver_version}}.tar.gz"
        dest: /home/vagrant
        remote_src: yes
        creates: "mapserver-{{mapserver_version}}.tar.gz"

    - name: Create build directory
      file:
        state: directory
        path: build

    - name: Run cmake
      command: "cmake -G 'Unix Makefiles' {{cmake_args}} ../mapserver-{{mapserver_version}}"
      args:
        chdir: build

    - name: Run make
      make:
        chdir: build

    - name: Run make install
      make:
        chdir: build
        target: install
      become: yes

    - name: Build MapServer RPM
      command: >-
        bin/fpm -s dir -t rpm -p /vagrant/out
        --name mapserver
        --version {{ mapserver_version }}
        --rpm-summary 'MapServer {{ mapserver_version }}'
        --iteration {{ rpm_release }}
        --vendor {{ vendor }}
        --maintainer '{{ vendor }} <{{ vendor_url }}>'
        --url https://mapserver.org/
        --rpm-dist el7
        --license X/MIT
        --depends freetype
        --depends libjpeg-turbo
        --depends libpng
        --depends libpqxx
        {% if with_cairo %}--depends cairo{% endif %}
        {% if with_exempi %}--depends exempi{% endif %}
        {% if with_fcgi %}--depends fcgi{% endif %}
        {% if with_fribidi %}--depends fribidi{% endif %}
        {% if with_gdal %}--depends gdal{% endif %}
        {% if with_geos %}--depends geos{% endif %}
        {% if with_harfbuzz %}--depends harfbuzz{% endif %}
        {% if with_gif %}--depends giflib{% endif %}
        {% if with_curl %}--depends libcurl{% endif %}
        {% if with_rsvg %}--depends librsvg2{% endif %}
        {% if with_proj %}--depends proj{% endif %}
        {% if with_protobufc %}--depends protobuf-c{% endif %}
        {% if with_libxml2 or with_sos or with_kml %}--depends libxml2{% endif %}
        /opt/mapserver
